"""Verify a Supabase backup by restoring it, not by trusting it.

WHY THIS EXISTS. On 2026-09-23 a backfill overwrote three `matches` rows with
data from three unrelated matches. Eight of the ten damaged columns were
recovered from a JSON file that happened to have been fetched twenty minutes
earlier for an unrelated reason. Three were not, and are gone. That was luck
standing in for a recovery plan, and a search of the repository for
`pg_dump` at the time returned only third-party hits inside a virtualenv.

The Supabase free tier schedules no backups - daily backups begin at Pro and
PITR is a paid add-on on top - so nothing else was covering this.

WHAT IS ACTUALLY AT RISK. Most of what Supabase holds is reproducible:
`predictions` with `source='backfill'` can be regenerated by
`ingest.replay_log run` from the corpus and the pinned artifact, and
`prediction_outcomes` rebuilt from `match_states`. Two things cannot be:

  * The LIVE predictions. A prediction made before its outcome existed cannot
    be recreated afterwards, because a replay emits `source='backfill'` rows
    by construction. They are also the only population whose accuracy means
    anything, which is what makes them the honest column on /accuracy.
  * The live-worker `matches` rows. Their ids come from Supabase's own
    sequence and they have no corpus counterpart - which is precisely why
    `team_a`, `team_b` and `venue_id` could not be restored after the
    incident.

THE WHOLE SCHEMA, NOT A CURATED LIST. The dump takes every table. A
hand-maintained list of "the tables that matter" is the same failure mode
`docs/column-census.md` exists to catch: a hardcoded enumeration that goes
stale the moment a migration adds something, and reports success while
omitting it. Twenty-two megabytes is not worth being clever about.

A BACKUP NOBODY HAS RESTORED IS NOT A BACKUP. The job restores into a
throwaway database and compares row counts and per-table content digests
against the source. A dump that cannot be restored, or restores short, fails
the job.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import psycopg

# pg_dump writes this as its last line on a successful run. Its absence is
# the signal a dump was truncated - by a dropped connection, a full disk, or
# a killed process - and truncation is the failure mode that matters most,
# because a half-written dump is a plausible-looking file that restores
# cleanly and is missing rows nobody counted.
COMPLETION_MARKER = "-- PostgreSQL database dump complete"

# A floor, not a target. The real check is the digest comparison below; this
# only catches the case where the dump is obviously not a dump - zero bytes,
# an error message, a stub - before anything spends time restoring it.
MIN_DUMP_BYTES = 200_000

# Tables that must not be empty, because an empty one means the dump ran
# against the wrong database or a broken connection returned a clean-looking
# but useless file. Chosen because they are the irreproducible ones: see the
# module docstring.
MUST_NOT_BE_EMPTY = ("predictions", "matches", "model_versions")


class BackupInvalid(RuntimeError):
    """The backup is not usable. Always fatal - never downgraded to a warning."""


def check_dump_file(path: Path) -> int:
    """Reject a dump that is empty, tiny, or truncated. Returns its size."""
    if not path.exists():
        raise BackupInvalid(f"no dump at {path}")

    size = path.stat().st_size
    if size < MIN_DUMP_BYTES:
        raise BackupInvalid(
            f"dump is {size:,} bytes, under the {MIN_DUMP_BYTES:,} floor. "
            f"A backup job that reports success while writing nothing is worse "
            f"than one that fails, because nobody looks again."
        )

    # Read the tail rather than the whole file: these run to tens of
    # megabytes and only the last line carries the marker.
    with path.open("rb") as handle:
        handle.seek(max(0, size - 4096))
        tail = handle.read().decode("utf-8", errors="replace")

    if COMPLETION_MARKER not in tail:
        raise BackupInvalid(
            f"dump does not end with {COMPLETION_MARKER!r}, so pg_dump did not "
            f"finish. The file is truncated and will restore short without "
            f"erroring."
        )
    return size


def table_digests(conn) -> dict[str, tuple[int, str]]:
    """Row count and a content digest for every table in `public`.

    The digest hashes each row's text representation, then aggregates ordered
    by that hash - so it is independent of physical row order, which a
    restore does not preserve. Comparing counts alone would miss a restore
    that produced the right number of wrong rows.
    """
    with conn.cursor() as cur:
        cur.execute(
            "SELECT tablename FROM pg_tables WHERE schemaname = 'public' ORDER BY tablename"
        )
        tables = [row[0] for row in cur.fetchall()]

        digests: dict[str, tuple[int, str]] = {}
        for table in tables:
            cur.execute(
                f'SELECT count(*), '  # noqa: S608 - identifier from pg_tables, not input
                f'coalesce(md5(string_agg(h, \'\' ORDER BY h)), \'empty\') '
                f'FROM (SELECT md5(t::text) AS h FROM public."{table}" t) s'
            )
            count, digest = cur.fetchone()
            digests[table] = (int(count), digest)
    return digests


def compare(source: dict[str, tuple[int, str]], restored: dict[str, tuple[int, str]]) -> None:
    """Raise unless the restored database matches the source exactly."""
    problems: list[str] = []

    missing = sorted(set(source) - set(restored))
    if missing:
        problems.append(f"tables absent after restore: {', '.join(missing)}")

    extra = sorted(set(restored) - set(source))
    if extra:
        problems.append(f"tables present only after restore: {', '.join(extra)}")

    for table in sorted(set(source) & set(restored)):
        want_rows, want_digest = source[table]
        got_rows, got_digest = restored[table]
        if want_rows != got_rows:
            problems.append(f"{table}: {want_rows:,} rows in source, {got_rows:,} restored")
        elif want_digest != got_digest:
            # Same count, different content. The case a row-count check alone
            # would pass, and the reason the digest exists.
            problems.append(
                f"{table}: {want_rows:,} rows both sides but the content digest differs"
            )

    for table in MUST_NOT_BE_EMPTY:
        if table not in source:
            problems.append(f"{table} is missing from the source database entirely")
        elif source[table][0] == 0:
            problems.append(
                f"{table} is empty in the SOURCE - the dump ran against the wrong "
                f"database, or a connection returned a clean but useless result"
            )

    if problems:
        raise BackupInvalid("backup verification failed:\n  " + "\n  ".join(problems))


def _summary(digests: dict[str, tuple[int, str]]) -> str:
    total = sum(count for count, _ in digests.values())
    lines = [f"{len(digests)} tables, {total:,} rows"]
    for table in sorted(digests, key=lambda t: -digests[t][0])[:8]:
        lines.append(f"    {digests[table][0]:>9,}  {table}")
    return "\n  ".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="ops.backup", description=__doc__)
    parser.add_argument("--dump", type=Path, required=True, help="the pg_dump output to check")
    parser.add_argument("--source-url", required=True, help="the database that was dumped")
    parser.add_argument("--restored-url", required=True, help="where the dump was restored")
    args = parser.parse_args(argv)

    try:
        size = check_dump_file(args.dump)
        print(f"dump file: {size:,} bytes, ends with the completion marker")

        with psycopg.connect(args.source_url, connect_timeout=30) as source_conn:
            source = table_digests(source_conn)
        print(f"  source:   {_summary(source)}")

        with psycopg.connect(args.restored_url, connect_timeout=30) as restored_conn:
            restored = table_digests(restored_conn)
        print(f"  restored: {_summary(restored)}")

        compare(source, restored)
    except BackupInvalid as failure:
        print(f"\nBACKUP INVALID\n{failure}", file=sys.stderr)
        return 1

    print("\nbackup verified: restored and matches the source row for row")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
