// GENERATED by api/src/agent_eval/tools.py - do not edit.
//
// Regenerate with:
//   python -m agent_eval.tools --emit-ts
//
// Definitions live in Python because the eval harness and the route both
// need byte-identical ones, and two copies are free to disagree - the same
// argument SPEC.md 10.1a makes against reimplementing the SQL guard in
// TypeScript. They are part of PROMPT_FINGERPRINT, so editing one without
// regenerating the other fails the staleness check in CI.

export const AGENT_TOOLS = [
  {
    "name": "resolve_entity",
    "description": "Resolve a player, team or venue name to ranked candidates with match scores. Call this before any tool that takes a name: the corpus stores abbreviated Cricsheet names ('V Kohli', not 'Virat Kohli'). Returns candidates rather than one answer - when several are plausible, ask the user which they meant instead of taking the top score.",
    "input_schema": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "The name as the user wrote it."
        },
        "kind": {
          "type": "string",
          "enum": [
            "player",
            "team",
            "venue"
          ]
        }
      },
      "required": [
        "name"
      ]
    }
  },
  {
    "name": "query_ball_data",
    "description": "Run one read-only SELECT against the ball-by-ball views: agent_deliveries, agent_matches, agent_players, agent_teams, agent_venues. Base tables are not readable.\n\nAGGREGATE IN SQL. The `rows` field carries at most 50 rows and is a SAMPLE for inspection, not the result set. Counting or summing by reading rows gives a wrong answer whenever there are more, and leaves you with no sample size to quote - use count(*), sum() and group by, and the number comes back with its own denominator.\n\nResponse fields: `row_count` is how many rows the query actually produced; `rows_shown` is how many are in `rows`; `truncated` is true when the database held more rows than the 1000-row limit allowed, meaning the result is not the whole answer and you must say so.\n\nA rejected query returns {error: 'query rejected', ref: <uuid>} and nothing else. Report that it was rejected; do not guess at which check refused it.",
    "input_schema": {
      "type": "object",
      "properties": {
        "sql": {
          "type": "string",
          "description": "One SELECT statement."
        }
      },
      "required": [
        "sql"
      ]
    }
  },
  {
    "name": "get_matchup",
    "description": "Head-to-head record for one batter against one bowler over the whole corpus. Returns `balls`, `runs`, `dismissals`, `strike_rate` and `average`. `balls` is the sample size and must appear alongside any rate you quote from it. Names must be resolved with resolve_entity first.",
    "input_schema": {
      "type": "object",
      "properties": {
        "batter": {
          "type": "string"
        },
        "bowler": {
          "type": "string"
        },
        "format": {
          "type": "string",
          "enum": [
            "ODI",
            "T20"
          ]
        }
      },
      "required": [
        "batter",
        "bowler"
      ]
    }
  },
  {
    "name": "get_player_form",
    "description": "Current ability estimate for a player. This returns a structured unavailability: estimating present ability needs a calibrated posterior with uncertainty, and the table holding it is empty until Phase 5. When it reports unavailable, say so. You may report the historical record from query_ball_data instead, but you must state that it describes what happened and is not an estimate of present ability.",
    "input_schema": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "kind": {
          "type": "string"
        }
      },
      "required": [
        "name"
      ]
    }
  },
  {
    "name": "get_live_prediction",
    "description": "The current full prediction set for a match, by its integer match id. Takes a bare integer only - a corpus reference like 'corpus:9337' is a different id space over the same fixtures and will not resolve here. If that is what you have, say so rather than converting it.",
    "input_schema": {
      "type": "object",
      "properties": {
        "match_id": {
          "type": "integer"
        }
      },
      "required": [
        "match_id"
      ]
    }
  }
];
